### ISSUE TITLE
 the request of code for datasets  organization

### ISSUE THREAD

**Issue by Guzaiwang** [MCG-NJU/MeMOTR#2]
Hi, thanks for your excellent work.
Could you upload the pre-processed code to organize the dataset?
(as follows):

```
DATADIR/
  ├── DanceTrack/
  │ ├── train/
  │ ├── val/
  │ ├── test/
  │ ├── train_seqmap.txt
  │ ├── val_seqmap.txt
  │ └── test_seqmap.txt
  ├── MOT17/
  │ ├── images/
  │ │ ├── train/
  │ │ └── test/
  │ └── gts/
  │   └── train/
  └── CrowdHuman/
    ├── images/
    │ ├── train/
    │ └── val/
    └── gts/
      ├── train/
      └── val/
```

**Comment by Guzaiwang** [comment]
When I downloaded the MOT_17 dataset and unzipped it, I got these files:
<img width="872" alt="image" src="https://github.com/MCG-NJU/MeMOTR/assets/48231203/8f722e0c-8c77-4f4b-b8ce-a62fa8e00ce4">
Could you give me some advice for the following dataset organisation?

**Comment by HELLORPG** [comment]
We upload the data organization code for MOT17. But I forgot to explain it. I will verify the correctness of this code immediately and update the documentation. At that time, I will reply to this issue to inform you. 

Thank you for your interest in our work.

**Comment by HELLORPG** [comment]
> When I downloaded the MOT_17 dataset and unzipped it, I got these files: <img alt="image" width="872" src="https://user-images.githubusercontent.com/48231203/276982072-8f722e0c-8c77-4f4b-b8ce-a62fa8e00ce4.png"> Could you give me some advice for the following dataset organisation?

We already updated ([this commit](https://github.com/MCG-NJU/MeMOTR/commit/8de231bc5c3601ff5f5c738c18ed1bb7d5b36325)) more details about data organization in our [doc](https://github.com/MCG-NJU/MeMOTR/blob/main/README.md). You can find the scripts [for MOT17](https://github.com/MCG-NJU/MeMOTR/blob/main/data/gen_mot17_gts.py) and [CrowdHuman](https://github.com/MCG-NJU/MeMOTR/blob/main/data/gen_crowdhuman_gts.py).

**Comment by Guzaiwang** [comment]
Thanks much for your kind and prompt response! 
It has solved my problem and I will close this issue.
