### ISSUE TITLE
Inference Program

### ISSUE THREAD

**Issue by JunJie1213855** [MCG-NJU/MeMOTR#23]
Hello, thank you for your contribution to multi-target tracking. Your algorithm is very powerful! But I want to use a model to infer video stream tracking, which means training, evaluation, and submission are not required. However, it seems that there are no files like inference.Py or demo.Py in your algorithm library. Could you guide me to complete the inference? Or Could you provide a program?

**Comment by HELLORPG** [comment]
Maybe you could refer to [demo.ipynb](https://github.com/MCG-NJU/MeMOTR/blob/main/tools/demo.ipynb).

**Comment by HELLORPG** [comment]
If you have other questions about demo scripts, you can re-open this issue or make a new one.
