### ISSUE TITLE
An error occurred while replicating the code

### ISSUE THREAD

**Issue by BelieveF** [MCG-NJU/MeMOTR#4]
Thank you for your excellent work. When I was training on the dancetrack dataset, I got an error: **RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x256 and 512x256)**. This error seems to say that the two matrices have different shapes, but I can't find the problematic block of code. Could you give me some guidance, please? Thank you very much.

**Comment by HELLORPG** [comment]
Which config file are you using?

**Comment by BelieveF** [comment]
> Which config file are you using?

Hello, I use this for training: MeMOTR-main/configs/train_dancetrack.yaml

**Comment by HELLORPG** [comment]
Can you give me more context about this error, perhaps a screenshot? There should be other text before this `RuntimeError`.

**Comment by BelieveF** [comment]
> Can you give me more context about this error, perhaps a screenshot? There should be other text before this `RuntimeError`.

Thank you for your reply. Error reported as follows：
![Uploading 1700291947640.png…]()

**Comment by BelieveF** [comment]
Thank you for your reply. Error reported as follows:
![1700291947640](https://github.com/MCG-NJU/MeMOTR/assets/86970890/8b6bd750-9acd-469f-aaac-7879898cfd56)

**Comment by HELLORPG** [comment]
I ran the same exp on my server, but this issue did not occur.

I notice that the error is caused by `raw_query_pos = self.ref_point_head(anchor_embed)` at line 99 in the file deformable_decoder.py. However, the same code is in [line 93](https://github.com/MCG-NJU/MeMOTR/blob/0a9542ce810225f9f96575708991da0105f303d7/models/deformable_decoder.py#L93), have you change some code in before it? 
Furthermore, can you check the shape of the tensor `anchor_embed`? This tensor should be 300x512 in our process, but it seems 300x256 in your code. I wonder to know that if you have modified the code related to it.

**Comment by BelieveF** [comment]
> I ran the same exp on my server, but this issue did not occur.
> 
> I notice that the error is caused by `raw_query_pos = self.ref_point_head(anchor_embed)` at line 99 in the file deformable_decoder.py. However, the same code is in [line 93](https://github.com/MCG-NJU/MeMOTR/blob/0a9542ce810225f9f96575708991da0105f303d7/models/deformable_decoder.py#L93), have you change some code in before it? Furthermore, can you check the shape of the tensor `anchor_embed`? This tensor should be 300x512 in our process, but it seems 300x256 in your code. I wonder to know that if you have modified the code related to it.

Your reply is very helpful to me. I will review the code and look at the tensor shape. I will let you know if I have solved your problem under this question, thanks again

**Comment by HELLORPG** [comment]
You're welcome. 
Looking forward to your good news.

**Comment by BelieveF** [comment]
> You're welcome. Looking forward to your good news.

Hello, with your help, I successfully solved my problem: the reason is that I modified the tensor information when debugging the code, which caused the problem. You can close the problem channel. Thank you very much for your help.

**Comment by HELLORPG** [comment]
I'm happy to help.
Have a nice day~:tada:
