### ISSUE TITLE
question about short_memory

### ISSUE THREAD

**Issue by BelieveF** [MCG-NJU/MeMOTR#5]
Hello, When I read your paper and reproduced the code, I had a question. You mentioned in your paper: **we fuse the outputs from two adjacent frames with an adaptive aggregation algorithm**. As shown in the red box below:
![S$JR}7L`P {M31@ OD}DAM7](https://github.com/MCG-NJU/MeMOTR/assets/86970890/235d9914-820c-4428-8f2d-12fabbc81321)

The implementation of this part in the code is as follows:
![%}JV9OB{J 0WVSJN 4Q))EU](https://github.com/MCG-NJU/MeMOTR/assets/86970890/774a1086-ba3f-4528-850c-862246e8fee8)

My question is as follows: **last_output_embed** represents the output of the previous frame, why is it not `tracks[b-1].last_output `but `tracks[b].last_output`.
I'm sorry to bother you again. If I have any misunderstanding, please advise me.

**Comment by HELLORPG** [comment]
In `last_output_embed = tracks[b].last_output`, the `b` is the corresponding batch, not the time step. In our experiments, as the batch size is set to 1, the `b` is 0 all the time.
We update the `last_output` in the later code.

**Comment by BelieveF** [comment]
> In `last_output_embed = tracks[b].last_output`, the `b` is the corresponding batch, not the time step. In our experiments, as the batch size is set to 1, the `b` is 0 all the time. We update the `last_output` in the later code.

Tanks for your reply!now i have saved my question!
